# Enhanced EKF Configuration for AUV Localization
# Place this in: config/ekf.yaml
# Based on robot_localization best practices

/**:
  ros__parameters:
    # EKF Node Parameters
    frequency: 30.0  # Update rate (Hz)
    sensor_timeout: 0.5  # Sensor timeout (seconds)
    two_d_mode: false  # False for 3D underwater operation
    
    # Transform frames
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    # Publishing options
    publish_tf: true
    publish_acceleration: true
    
    # Sensor Configuration
    # Format: [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    
    # ---------- IMU Sensor ----------
    imu0: /imu/data
    imu0_config: [
      false, false, false,  # x, y, z (position - IMU doesn't provide)
      true,  true,  true,   # roll, pitch, yaw (orientation)
      false, false, false,  # vx, vy, vz (linear velocity - IMU doesn't provide)
      true,  true,  true,   # vroll, vpitch, vyaw (angular velocity)
      true,  true,  true    # ax, ay, az (linear acceleration)
    ]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
    
    # IMU noise parameters (tune based on your sensor)
    imu0_linear_acceleration_rejection_threshold: 3.0
    imu0_angular_velocity_rejection_threshold: 2.0
    imu0_orientation_rejection_threshold: 1.5
    
    # ---------- Visual