%YAML:1.0
SLAM.alg: orb_slam3

#--------------------------------------------------------------------------------------------
# ORB-SLAM3 Stereo Configuration
#--------------------------------------------------------------------------------------------
File.version: "1.0"

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# LEFT CAMERA (Camera1)
Camera1.fx: 474.896
Camera1.fy: 474.896
Camera1.cx: 400.0
Camera1.cy: 300.0

Camera1.k1: 0.262383
Camera1.k2: -0.953104
Camera1.p1: -0.005358
Camera1.p2: 0.002628
Camera1.k3: 1.163314

# RIGHT CAMERA (Camera2)
Camera2.fx: 474.896
Camera2.fy: 474.896
Camera2.cx: 400.0
Camera2.cy: 300.0

Camera2.k1: 0.262383
Camera2.k2: -0.953104
Camera2.p1: -0.005358
Camera2.p2: 0.002628
Camera2.k3: 1.163314

#--------------------------------------------------------------------------------------------
# Stereo Configuration
#--------------------------------------------------------------------------------------------
# Stereo baseline in meters (distance between cameras)
Stereo.b: 0.075

# Stereo depth threshold (increase for better stability)
Stereo.ThDepth: 35.0

# Transformation from Camera1 to Camera2 (left to right)
Stereo.T_c1_c2: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ 1., 0., 0., 0.075,
           0., 1., 0., 0.,
           0., 0., 1., 0.,
           0., 0., 0., 1. ]

#--------------------------------------------------------------------------------------------
# Image Settings
#--------------------------------------------------------------------------------------------
Camera.fps: 30
Camera.RGB: 1
Camera.width: 800
Camera.height: 600

#--------------------------------------------------------------------------------------------
# ORB Feature Extractor
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 30
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 10
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 3

#--------------------------------------------------------------------------------------------
# Tracking Parameters
#--------------------------------------------------------------------------------------------
# Maximum number of frames for tracking
Tracking.maxFrames: 3000

# Initial tracking threshold
Tracking.th: 7

# Keyframe insertion thresholds
KeyFrame.minFrames: 0
KeyFrame.maxFrames: 300

#--------------------------------------------------------------------------------------------
# Loop Closing
#--------------------------------------------------------------------------------------------
LoopClosing.enabled: 1

#--------------------------------------------------------------------------------------------
# Viewer Settings
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -1.0
Viewer.ViewpointZ: -2.5
Viewer.ViewpointF: 500.0