### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        two_d_mode: false
        publish_tf: true
        publish_acceleration: false

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom # Crucial for sim without explicit map

        # --- Sensor Inputs ---
        odom0: /optical_flow/twist # Optical Flow Velocity
        odom0_config: [false, false, false, false, false, false,
                       true,  true,  false, # Use Vx, Vy from Optical Flow
                       false, false, false, false, false, false]
        odom0_queue_size: 5
        odom0_nodelay: false
        odom0_differential: false
        odom0_relative: false # Assuming Twist is published in base_link frame

        imu0: /imu/data # Simulated IMU
        imu0_config: [false, false, false,
                      true,  true,  true,  # Use full Orientation R, P, Y
                      false, false, false,
                      true,  true,  true,  # Use Angular Velocity
                      true,  true,  true]  # Use Linear Acceleration (Simulated accel is usually good)
        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: false # Assuming IMU frame = base_link or static TF provided
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true

        pose0: /depth/pose # Simulated Depth from Depth Processor
        pose0_config: [false, false, true, # Use Z position
                       false, false, false,
                       false, false, false, false, false, false,
                       false, false, false]
        pose0_differential: false
        pose0_relative: false # Z position is in the odom frame
        pose0_queue_size: 2
        pose0_nodelay: false
        pose0_rejection_threshold: 2.0 # Can be tighter in sim

        # --- Process Noise Covariance (Tune for Sim) ---
        # Start with slightly lower values than real robot, especially for velocity/rates
        process_noise_covariance: [0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.02,  0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0, # Reduced Vel noise
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.02,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.02,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.01,  0.0,   0.0,  0.0,  0.0,  0.0, # Reduced Rate noise
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.01,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.02, 0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.01, 0.0,  0.0, # Reduced Accel noise
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.01, 0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.01]


        # --- Initial State Covariance ---
        initial_estimate_covariance: [1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0, # Very certain initial pose in sim
                                      0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                      0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                      0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                      0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                      0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0, # Very certain initial vel = 0
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,   0.0,   0.0,  0.0,  0.0,  0.0,
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9,  0.0,   0.0,  0.0,  0.0,  0.0, # Very certain initial rates = 0
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   1e-9,  0.0,  0.0,  0.0,  0.0,
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   1e-9, 0.0,  0.0,  0.0,
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  1e-6, 0.0,  0.0, # Accel bias uncertainty (if used)
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  1e-6, 0.0,
                                      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  1e-6]