# Used by: simple_thruster_mapper.py

simple_thruster_mapper:
  ros__parameters:
    # Thrust limits
    max_thrust: 10.0
    min_thrust: -10.0
    
    # Scaling factor (tune based on actual performance)
    thrust_scale: 3.0
    
    # Deadband (ignore small commands)
    deadband_threshold: 0.05
    
    # Rate limiting (prevent sudden changes)
    max_thrust_rate: 5.0  # units/second
    
    # Individual thruster trim (for hardware calibration)
    thruster_trim:
      t1: 1.0  # Front-left
      t2: 1.0  # Front-right
      t3: 1.0  # Back-left
      t4: 1.0  # Back-right
      t5: 1.0  # Vertical-left
      t6: 1.0  # Vertical-right